language: php

php:
  - "5.4"
  - "5.3"

before_install:
  - cd ../../
  - git clone git://github.com/laravel/laravel.git
  - mv ./orchestral/melody ./laravel/bundles/melody
  - cd ./laravel
  - php artisan bundle:install orchestra
  - echo "<?php return array('orchestra' => array('auto' => true, 'handles' => 'orchestra'), 'melody');" > ./application/bundles.php

script: "phpunit --coverage-text --configuration bundles/melody/phpunit.xml"
